apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: va-api
  template:
    metadata:
      labels:
        app: va-api
    spec:
      containers:
      - name: va-api
        image: va-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Add other environment variables as needed