name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore VA.sln

    - name: Build
      run: dotnet build VA.sln --configuration Release --no-restore

    - name: Test
      run:  dotnet test VA.sln --no-build --verbosity normal

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t vertical-slice-architecture:${{ github.sha }} -f VA.API/Dockerfile .
          
